services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/database/user
      POSTGRES_PASSWORD_FILE: /run/secrets/database/password
      POSTGRES_DB_FILE: /run/secrets/database/name
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./secrets/database:/run/secrets/database
volumes:
  postgres-data: